---
- name: "Check if NGINX is installed"
  package_facts:
    manager: "auto"

- name: check if nginx is already installed
  debug:
   msg: "NGINX Found"
  when: "'nginx' in ansible_facts.packages"

- name: "NGINX test result"
  debug:
    msg: "NGINX NOT found"
  when: "'nginx' not in ansible_facts.packages"
